### ISSUE TITLE
setValue does not work correctly with focused fields

### ISSUE THREAD

**Issue by Chekote** [minkphp/MinkSelenium2Driver#198]
This took me a long time to track down, and it's somewhat difficult to explain, but here goes...

This is causing tests to fail on my project because I'm testing pages that have certain fields auto-focused depending on user actions.

OS: Mac OS X 10.10
Browser: Firefox 31.4.0esr, 33.1.1, 34.0.5
Selenium: 2.44

Unfortunately it's difficult to create a pull request to demonstrate this because this repo uses tests and fixtures defined in one of it's vendors folders, which is outside of version control. So I'm going to have to post details here instead.

I had a lot of difficulty creating a failing test that would illustrate this issue, because I could not get the field to focus during testing using evaluateScript() or even by adding a simple button with an onclick="blablabla.focus()", because for some reason that didn't work either! *pulls hair out*.

The only way I can get this test to fail is to add a function that is called by a button... bizarre. Anyway, onto the details:

Add the following snippet to the end of the body tag in `/vendor/behat/mink/driver-testsuite/web-fixtures/basic_form.html`:

```html
    <button onclick="doFocus()">Focus</button>

    <script>
      function doFocus() {
        document.getElementById('lastn').focus();
      }
    </script>
```

Then drop the following into the GeneralTest class in `/vendor/behat/mink/driver-testsuite/tests/Form/GeneralTest.php`:

```php
    public function testFillFocusedTextField()
    {
        $session = $this->getSession();

        $session->visit($this->pathTo('/basic_form.html'));

        $page = $this->getSession()->getPage();
        $page->pressButton('Focus');

        $webAssert = $this->getAssertSession();
        $field = $webAssert->fieldExists('last_name');
        $field->setValue('Chekote');

        $this->assertEquals('Chekote', $field->getValue());
    }
```

Then run the test with `phpunit --filter "testFillFocusedTextField"`

It shouldn't matter where the caret is when the field is focused, because the Selenium2Driver::setValue() method prepends a backspace and a delete keystroke for each existing character to the value before passing it to the postValue method. This *should* mean that the existing value will be deleted regardless of where the caret is in the field.

Unfortunately, it is failing with the caret being anywhere except the very end of the existing value. It appears that when the field is already focused, there are two possible scenarios:

1. If the caret is at the very beginning of the existing value, then only the first "delete" keystroke is processed, and the new value inserted. So in the test above, this results in "Lastname" changing to "Chekoteastname", instead of the expected "Chekote".
2. If the caret is anywhere within the existing value, then all of the "delete" keystrokes seem to be completely ignored. A few examples:

```
Caret positon:    Result:
L|astname          Chekoteastname
La|stname          Chekotestname
Las|tname          Chekotetname
Last|name          Chekotename
```

I can fix this on my machine with a call to $element->clear() before calling the postValue(), but I understand that this probably introduces issues with events (which is why I'm guessing it was removed in 23ec6b4d4aaba1a6de8affe097a95682b90022bf).

Any advice / help would be greatly appreciated.

**Comment by aik099** [comment]
Isn't this somehow related to #194 ?

**Comment by aik099** [comment]
> I tried to create a failing tests to indicate this issue, but without pulling in something like jQuery, I couldn't get it to focus the field automatically. 

jQuery is available in Selenium2 tests if you need it.

> 1. If the caret is at the very beginning of the existing value, then the first character is deleted, and the new value inserted. So in the test above, this results in "Chekoteastname".
> 2. If the caret is anywhere within the existing value, only the backspace characters seem to be taking effect. A few examples:

I see. What OS you're running Selenium Server on. The Delete+Backspace trick was chosen since it should clear field value regardless of cursor position. And it also seems to be OS agnostic (works on Mac/Windows/Linux). However I guess it doesn't work as expected in your case.

**Comment by aik099** [comment]
For me (Mac, OSX 10.9.5) pressing `backspace, delete, backspace, delete, backspace, delete, ... new-value` clears the value properly (I've tried to do this by hand in the Google Chrome).

**Comment by Chekote** [comment]
Howdy,

Thanks for the responses. I did review #194, but I couldn't find a connection.

I see that jQuery is in the project now, I'll update my test to utilize that for completeness.

I'm using Mac OS X 10.10 and Firefox 34.0.5. I can confirm your assessment that pressing the keys manually does work. In fact, this entire scenario works just fine if performed manually. It is only when using Selenium2 that the problem occurs.

**Comment by aik099** [comment]
If you have Mavericks at hand, then please try it or maybe different browser or browser version.

It also can be bug in latest Selenium Server not working with latest Firefox.

**Comment by Chekote** [comment]
I can certainly give that a try. However, the problem only arose after I pulled down an update which included 23ec6b4d4aaba1a6de8affe097a95682b90022bf. Prior to that, my current setup can run all my tests just fine.

It could certainly be a bug with Firefox/Selenium that's just been exposed via 23ec6b4d4aaba1a6de8affe097a95682b90022bf, so I'll try it and let you know.

**Comment by Chekote** [comment]
OK, so I've updated the original post with an actual failing test and instructions on how to run it in this repo. If you could try it against your Mavericks setup that'd be awesome. If not, I'll try to borrow a colleagues machine to test it.

**Comment by aik099** [comment]
My setup:
Firefox: 27.0
OS: OSX 10.9.5, Mavericks
Selenium Server: 2.44

I can confirm that in my setup doing `str_repeat(Key::BACKSPACE . Key::DELETE, $existingValueLength)` (which produces 48 symbols (because UTF-16 encoded) long string for 8 symbols long value) does only remove 1st char in the input, when it's focused.

**Comment by Chekote** [comment]
I've updated to the following and the problem still persists:

OS: Mac OS X 10.10.2
Browser: Firefox 35.0.1
Selenium: 2.44

**Comment by aik099** [comment]
Any ideas on fixing, @Chekote ? @stof , your thoughts?

**Comment by Chekote** [comment]
Not at the moment. I have a sneaking suspision that it may be a bug with the Selenium driver itself.

The only way I've managed to get it to work is to place an `$element->clear()` before the `$element->postValue(array('value' => array($value)));` at the end of `\Behat\Mink\Driver\Selenium2Driver::setValue()`. However, I'm not sure if this causes problems with the browser events.

**Comment by aik099** [comment]
We can eliminate selenium server problem by trying using one of previous versions (less than 2.44).

**Comment by stof** [comment]
The issue is not Selenium 2.44. It is Firefox 35. Selenium 2.44 is not compatible with changes done in Firefox 35, which is now forcing extensions to use the safer way to pass objects from the priviledged code (of the extension) to the code of the page. Stable versions of Selenium are using the old API which has been removed in Gecko 35 (yeah, the Selenium team waited until the removal of the old API before starting the upgrade process to the new API). This means that any method executing JS on the page will not work with Firefox 35.

So there is 2 ways to fix it:

- use an older version of Firefox (Selenium 2.44 officially supports Firefox 24, 31, 32 and 33)
- build selenium from source so that you have a version with https://github.com/SeleniumHQ/selenium/commit/66d55c84463d66740e5a2213c521eee36eda719e included (note that their CI setup runs Firefox 34 now, but running Firefox 35 has been reverted though).

It looks like it is safer to stick to ESR versions of Firefox when using Selenium as their release cycle is much longer than the Firefox one.

**Comment by aik099** [comment]
We can control what Firefox version is used on Travis (but we don't use that Travis feature currently), but at my home computer I have Firefox 35. So I end up in all tests failing I guess.

Is it worth to downgrade to Firefox 33 or wait a few months before Selenium 2.45 will be released?

**Comment by stof** [comment]
Travis is providing the latest ESR release (currently Firefox 31), so there is no need to force a version there IMO. The ESR usage is already enough (and it avoids forgetting to bump to the new ESR every 9 months)

**Comment by Chekote** [comment]
I have just tested this with Firefox 33.1.1, and the problem persists.

**Comment by aik099** [comment]
@Chekote and with Firefox 31 as well?

**Comment by Chekote** [comment]
I am not familiar with either of those issues (or the way you are wording them). The problem that is persisting is the one outlined in my original post of this issue.

**Comment by Chekote** [comment]
The problem persists with Firefox 31.4.0esr

**Comment by Chekote** [comment]
Just noticed a Selenium update was released, but no luck. The test is still failing with the following

OS: Mac OS X 10.10.2
Browser: Firefox 31.4.0esr & 36.0.1
Selenium: 2.45

**Comment by aik099** [comment]
Passes in Google Chrome. I guess it's still a bug in Selenium server. Can somebody report it to them?

**Comment by Chekote** [comment]
I'm looking into it now. I'll post an update shortly.

**Comment by Chekote** [comment]
OK, I have the following test that is failing, so it's definitely not a Mink issue:

focustest.html:
```html
<!DOCTYPE html>
<html>
<head>
    <title>Focus Test</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
</head>
<body>
    <input id="field" name="data" value="Initial Value" type="text" />

    <button id="focusbtn" onclick="doFocus()">Focus</button>

    <script>
      function doFocus() {
        document.getElementById('field').focus();
      }
    </script>
</body>
</html>
```

test.php:
```php
<?php

class WebTest extends PHPUnit_Extensions_Selenium2TestCase {

  function setUp() {
    $this->setBrowser('firefox');
    $this->setBrowserUrl('http://localhost/');
  }

  function testFillFocusedField() {
	$value = 'Chekote';

    $this->url('/focustest.html');
    $this->byId('focusbtn')->click();

    // get the field value current length, and add backspace/delete keystrokes to remove it
    $field = $this->byId('field');
    for ($i = 0; $i < strlen($field->value()); $i++) {
      $deletes = PHPUnit_Extensions_Selenium2TestCase_Keys::BACKSPACE . PHPUnit_Extensions_Selenium2TestCase_Keys::DELETE;
    }

    $this->keys($deletes . $value);

    $this->assertEquals($value, $field->value());
  }
}
```

Result:
```
$ phpunit test.php
PHPUnit 4.3.5 by Sebastian Bergmann.

F

Time: 2.66 seconds, Memory: 3.75Mb

There was 1 failure:

1) WebTest::testFillFocusedField
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Chekote'
+'Chekotenitial Value'

test.php:24
```

**Comment by Chekote** [comment]
I have opened a ticket with Selenium here: https://code.google.com/p/selenium/issues/detail?id=8589

**Comment by Chekote** [comment]
I have a correction to make:

My previous test for recreating this issue with Selenium had a typo which was causing the test to fail. As soon as I fixed this, the test passed. Therefore, this is *NOT* a Selenium issue. I've updated the Selenium ticket accordingly.

I have updated my comment above to illustrate that Selenium is functioning correctly. So we're back to looking at the Mink Selenium2Driver to determine what's causing this problem.

**Comment by aik099** [comment]
What WebDriver call the `keys` method does? I presume it's `sendKeys`. If so, then it also doesn't clear previous field value OR if it does, then this might cause double `change` event to be fired in JS (on clear and on value change).

**Comment by Chekote** [comment]
I'm not exactly sure. The PHPUnit_Extensions_Selenium2TestCase class uses a `@method` annotation to declare that method, and there's no implementation of it within the source that I have. I'm still digging though...

**Comment by aik099** [comment]
I've looked up and class, that does that is: https://github.com/giorgiosironi/phpunit-selenium/blob/master/PHPUnit/Extensions/Selenium2TestCase/SessionCommand/Keys.php , which is basically posting the value without changes.

Looks like the same `postValue` call we're making using Instaclick WebDriver. Maybe there is something in between that transforms the value in `Instaclick WebDriver` library.

**Comment by aik099** [comment]
Anyway it's easier to debug now and compare what actual value and API call is made using WebDriver.

**Comment by aik099** [comment]
Just out of curiosity I've executed https://github.com/minkphp/MinkSelenium2Driver/issues/198#issuecomment-77910408 test locally and it failed:
```
Failed asserting that two strings are equal.
Expected :Chekote
Actual   :Chekotenitial Value
```

**Comment by Chekote** [comment]
I'm continuing to investigate, but here are my findings so far: I'm focusing on two methods:

* Instaclick AbstractWebDriver's curl()
* PHPUnit_Extensions_Selenium2TestCase_Driver's curl()

These both seem to be the closest I can get to Selenium itself, so I'm examining what's happening here and seeing where the implementations differ. So far I've come across two differences:

* Selenium2Driver is sending the new value as a string in the first element of the 'value' array, whereas PHPUnit is sending the new value as an array of keys in the 'value' array.
* Selenium2Driver is calling Seleniums `value` command, whereas PHPUnit is calling the `/keys` command.

To investigate the first problem, I have already modifyied the Selenium2Drvier::setValue method as follows:

```patch
diff --git a/src/Selenium2Driver.php b/src/Selenium2Driver.php
index 3fceb1c..f0143e2 100755
--- a/src/Selenium2Driver.php
+++ b/src/Selenium2Driver.php
@@ -669,16 +669,22 @@ JS;
             }
         }
 
-        $value = strval($value);
+        $keys = str_split(strval($value));
 
         if (in_array($elementName, array('input', 'textarea'))) {
             $existingValueLength = strlen($element->attribute('value'));
             // Add the TAB key to ensure we unfocus the field as browsers are triggering the change event only
             // after leaving the field.
-            $value = str_repeat(Key::BACKSPACE . Key::DELETE, $existingValueLength) . $value . Key::TAB;
+            for ($i = 0; $i < $existingValueLength; ++$i) {
+              array_unshift($keys, Key::BACKSPACE);
+              array_unshift($keys, Key::DELETE);
+            }
+
+            $keys[] = Key::TAB;
         }
 
-        $element->postValue(array('value' => array($value)));
+        $element->postValue(array('value' => $keys));
     }
 
     /**
```

This did result in both PHPUnit and Behat environments sending the new value as an array of keystrokes, but the bug persisted. So I do not believe the keys array vs keys string to be the problem. 

I'm currently investigating the `value` vs `keys` approach.

**Comment by Chekote** [comment]
@aik099 I just saw your comment. I'm not sure why the test would be failing on your environment, as I've been running it all day and it's consistently passing for me. I'm working with the following versions at the moment:

Mac OS X 10.10.2
Firefox 34.0.5
PHPUnit 4.5.0
Selenium 2.44

**Comment by aik099** [comment]
@Chekote you said, that you've made a 100% failing example using PHPUnit's Selenium extension, but then you told that it was failing due typo. I can assure you that it's failing for me at 100% cases. Also, as expected failing test using Mink is also failing at 100% cases.

So nothing is passing on my side.

**Comment by aik099** [comment]
And you're using Firefox 34 where Selenium works, but on Firefox 36 it doesn't work.

**Comment by Chekote** [comment]
The original was failing due to a typo, sorry for the confusion. But I've corrected it now and the example above is passing in my environment. I've copy and pasted the code directly from the example above to ensure that there are no other typos in there, and it's passing.

I've not been able to move past Firefox 34 yet. If I move to Firefox 35 and/or Selenium 2.45 I get a whole host of other problems.

**Comment by aik099** [comment]
You can test on Sauce Labs or BrowserStack as well.

> The original 

I see 2 tests:
* one using Mink: https://github.com/minkphp/MinkSelenium2Driver/issues/198#issue-56439763
* one not using Mink: https://github.com/minkphp/MinkSelenium2Driver/issues/198#issuecomment-77910408

Both are failing for me.

Maybe on Firefox 34 one of them passes, I don't know.

**Comment by Chekote** [comment]
I'll take another look at everything, it's possible I'm just getting turned around.

**Comment by Chekote** [comment]
Well this is embarrassing. You were right, both tests are failing. I overlooked some changes I had made during my tests. I'm just going to bury my head in shame now...

I've re-opened the ticket with Selenium's new Github repo: https://github.com/SeleniumHQ/selenium/issues/340

**Comment by perk11** [comment]
Still experiencing this issue with FF36 and 38. Strangely enough it disappears, when I remove ` . Key::TAB` at the end of this line https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php#L662

**Comment by stof** [comment]
@perk11 which selenium version are you using ?

**Comment by perk11** [comment]
@stof 2.46

**Comment by andreabenfatto** [comment]
Same behaviour for #213

**Comment by Chekote** [comment]
This has been fixed as of Firefox 44 and Selenium 2.51.0. I'm not sure at exactly what version it was resolved. I've already closed the Selenium issue.
